In [3]:
import numpy as np

In [4]:
# Arreglos

arr1 = np.array([1,2,3])

In [5]:
print(arr1)

[1 2 3]


In [6]:
type(arr1)

numpy.ndarray

In [7]:
dir([])

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [8]:
dir(arr1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [9]:
lista1 = [1,1.1,"", True]
np.array(lista1)

array(['1', '1.1', '', 'True'], dtype='<U32')

In [10]:
arr2 = np.asarray([1, 2, 3, 4, 5])

In [11]:
arr2.shape

(5,)

In [12]:
arr2.dtype

dtype('int64')

In [13]:
len(arr2)

5

In [14]:
# Lista de listas
lista2 = [[1,2,3],[4,5,6]]

In [15]:
type(lista2)

list

In [16]:
lista2[0][0]

1

In [18]:
arr3 = np.asarray([[1,2,3],[4,5,6]])

In [19]:
type(arr3)

numpy.ndarray

In [20]:
len(arr3)

2

In [22]:
arr3.shape

(2, 3)

In [21]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr3[0,0]

np.int64(1)

In [31]:
arr3[0,1]

np.int64(2)

In [32]:
arr3[:, :2]

array([[1, 2],
       [4, 5]])

In [33]:
arr3.size

6

In [34]:
arr3.min()

np.int64(1)

In [35]:
arr3.max()

np.int64(6)

In [23]:
800*800*3

1920000

In [24]:
arr3.mean()

np.float64(3.5)

In [37]:
arr3.std()

np.float64(1.707825127659933)

In [38]:
np.median(arr3)

np.float64(3.5)

In [25]:
# 0. Arit.
arr3 + 1 #Element-wise

array([[2, 3, 4],
       [5, 6, 7]])

In [26]:
arr3-10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [40]:
arr3*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [41]:
arr3/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [42]:
arr3**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [48]:
arr3 + arr3

array([[1000,    4,    6],
       [   8,   10,   12]])

In [57]:
arr3

array([[500,   2,   3],
       [  4,   5,   6]])

In [58]:
# Copiar arreglos

tmp=arr3

In [59]:
tmp

array([[500,   2,   3],
       [  4,   5,   6]])

In [61]:
arr3[0, 0] = 100

In [62]:
arr3

array([[100,   2,   3],
       [  4,   5,   6]])

In [63]:
tmp

array([[100,   2,   3],
       [  4,   5,   6]])

In [64]:
# Método ideal
tmp = arr3.copy()

In [65]:
arr3[0, 0] = 500

In [66]:
arr3

array([[500,   2,   3],
       [  4,   5,   6]])

In [67]:
tmp	

array([[100,   2,   3],
       [  4,   5,   6]])

In [68]:
print(arr3, "\n", tmp)

[[500   2   3]
 [  4   5   6]] 
 [[100   2   3]
 [  4   5   6]]


Random

In [69]:
np.random.random()

0.30988350925434516

In [71]:
np.random.randint(10)

8

In [54]:
np.random.randint(10, size=(10, 10))

array([[2, 6, 1, 3, 9, 6, 1, 0, 1, 9],
       [0, 0, 9, 3, 4, 0, 0, 4, 1, 7],
       [3, 2, 4, 7, 2, 4, 8, 0, 7, 9],
       [3, 4, 6, 1, 5, 6, 2, 1, 8, 3],
       [5, 0, 2, 6, 2, 4, 4, 6, 3, 0],
       [6, 4, 7, 6, 7, 1, 5, 7, 9, 2],
       [4, 8, 1, 2, 1, 1, 3, 5, 9, 0],
       [8, 1, 6, 3, 3, 5, 9, 7, 9, 2],
       [3, 3, 3, 8, 6, 9, 7, 6, 3, 9],
       [6, 6, 6, 1, 3, 4, 3, 1, 0, 5]], dtype=int32)

In [55]:
np.random.seed(123)

In [56]:
np.random.randint(10, size=(10, 10))

array([[2, 2, 6, 1, 3, 9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3, 4, 0, 0, 4, 1],
       [7, 3, 2, 4, 7, 2, 4, 8, 0, 7],
       [9, 3, 4, 6, 1, 5, 6, 2, 1, 8],
       [3, 5, 0, 2, 6, 2, 4, 4, 6, 3],
       [0, 6, 4, 7, 6, 7, 1, 5, 7, 9],
       [2, 4, 8, 1, 2, 1, 1, 3, 5, 9],
       [0, 8, 1, 6, 3, 3, 5, 9, 7, 9],
       [2, 3, 3, 3, 8, 6, 9, 7, 6, 3],
       [9, 6, 6, 6, 1, 3, 4, 3, 1, 0]], dtype=int32)