In [1]:
import numpy as np

In [3]:
# Arreglos

arr1 = np.array([1,2,3])

In [4]:
print(arr1)

[1 2 3]


In [5]:
type(arr1)

numpy.ndarray

In [8]:
lista1 = [1,1.1,"", True]
np.array(lista1)

array(['1', '1.1', '', 'True'], dtype='<U32')

In [9]:
arr2 = np.asarray([1, 2, 3, 4, 5])

In [10]:
arr2.shape

(5,)

In [11]:
arr2.dtype

dtype('int64')

In [12]:
len(arr2)

5

In [26]:
# Lista de listas
lista2 = [[1,2,3],[4,5,6]]

In [27]:
arr3 = np.asarray([[1,2,3],[4,5,6]])

In [28]:
arr3.shape

(2, 3)

In [29]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr3[0,0]

np.int64(1)

In [31]:
arr3[0,1]

np.int64(2)

In [32]:
arr3[:, :2]

array([[1, 2],
       [4, 5]])

In [33]:
arr3.size

6

In [34]:
arr3.min()

np.int64(1)

In [35]:
arr3.max()

np.int64(6)

In [36]:
arr3.mean

<function ndarray.mean>

In [37]:
arr3.std()

np.float64(1.707825127659933)

In [38]:
np.median(arr3)

np.float64(3.5)

In [39]:
# 0. Arit.
arr3 + 1 #Element-wise

array([[2, 3, 4],
       [5, 6, 7]])

In [40]:
arr3*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [41]:
arr3/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [42]:
arr3**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [43]:
arr3 + arr3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [45]:
tmp = arr3.copy()

In [46]:
arr3[0, 0] = 500

In [48]:
print(arr3, tmp)

[[500   2   3]
 [  4   5   6]] [[1 2 3]
 [4 5 6]]


Random

In [49]:
np.random.random()

0.8577409653540101

In [50]:
np.random.randint(10)

3

In [68]:
np.random.randint(10, size=(10, 10))

array([[2, 1, 0, 8, 2, 2, 4, 6, 3, 2],
       [1, 0, 7, 9, 0, 7, 8, 4, 7, 5],
       [1, 7, 7, 8, 2, 2, 1, 3, 8, 4],
       [0, 9, 2, 2, 3, 1, 7, 2, 9, 0],
       [5, 1, 2, 9, 1, 9, 9, 9, 7, 6],
       [7, 2, 5, 7, 2, 6, 8, 1, 2, 6],
       [7, 1, 1, 0, 1, 5, 0, 9, 5, 8],
       [5, 7, 5, 1, 1, 1, 9, 1, 9, 3],
       [4, 7, 0, 8, 7, 3, 2, 0, 4, 6],
       [0, 5, 1, 2, 6, 1, 3, 1, 3, 0]], dtype=int32)

In [74]:
np.random.seed(123)

In [76]:
np.random.randint(10, size=(10, 10))

array([[5, 8, 6, 8, 9, 1, 0, 3, 1, 3],
       [4, 7, 6, 1, 4, 3, 3, 7, 6, 8],
       [6, 4, 4, 7, 0, 0, 9, 8, 8, 4],
       [8, 6, 1, 6, 8, 7, 9, 1, 7, 1],
       [7, 9, 8, 7, 1, 3, 1, 8, 7, 5],
       [1, 2, 5, 2, 2, 9, 3, 2, 6, 7],
       [9, 1, 3, 8, 3, 7, 9, 9, 3, 3],
       [5, 6, 0, 8, 7, 7, 4, 4, 5, 0],
       [8, 9, 2, 5, 1, 5, 9, 2, 4, 3],
       [0, 3, 7, 7, 2, 5, 1, 7, 5, 9]], dtype=int32)